### ISSUE TITLE
Interesting! Also the website Blotter is great!

### ISSUE THREAD

**Issue by keithorange** [blotterfyi/velocity#1]
I liked these projects of yours. I'm also working on finance apps and LLM's. I liked your design here but youre website is a good idea. To track WallStreetBets and how they performed is very interesting.

You can expand that website to have AI agents analyzing trades on /r/personalfinance or wallstreetbets etc. 

You can also use AutoGen

**Comment by blotterfyi** [comment]
Thank you so much.
